In [ ]:
import numpy as np
from scipy.spatial.distance import euclidean

def GraphPreprocessing(nodes, edges):
    """nodes, edges를 받아 converted nodes, edges를 반환"""
    adj = make_adjacency_matrix(nodes, edges)  # 인접 행렬 생성
    converted_nodes = convert_nodes(nodes)  # 노드 변환
    converted_edges = convert_edges_to_links(converted_nodes, adj)  # 엣지 변환
    return converted_nodes, converted_edges


def make_adjacency_matrix(nodes, edges):
    """인접 행렬 생성"""
    num_nodes = len(nodes)
    adj = np.zeros((num_nodes, num_nodes))

    for start, end in edges:
        adj[start, end] = 1
        adj[end, start] = 1  # 양방향 처리
    
    return adj


def convert_nodes(nodes):
    """노드 리스트 변환 수행"""
    converted_nodes = []
    for i, (node_type, coords) in enumerate(nodes):
        node_info = {
            'id': i,
            'type': node_type,
            'coords': coords,
        }
        converted_nodes.append(node_info)
    return converted_nodes


def convert_edges_to_links(converted_nodes, adj_matrix):
    """엣지를 링크 리스트로 변환"""
    links = []
    num_nodes = len(converted_nodes)
    
    for i in range(num_nodes):
        for j in range(i + 1, num_nodes):
            if adj_matrix[i, j] == 1:  # 연결된 경우
                distance = euclidean(converted_nodes[i]['coords'], converted_nodes[j]['coords'])
                
                # S-S 연결이면 highway, 나머지는 urban
                road_type = 'highway' if (converted_nodes[i]['type'] == 'S' and converted_nodes[j]['type'] == 'S') else 'urban'
                
                links.append({'start': i, 'end': j, 'distance': distance, 'road_type': road_type})
                links.append({'start': j, 'end': i, 'distance': distance, 'road_type': road_type})  # 양방향 추가

    return links



In [8]:

# 예제 데이터
dummy_nodes = [['H', (10, 10)], ['I', (5, 8)], ['S', (7, 2)], ['C', (6, 0)], 
               ['S', (2, 7)], ['C', (5, 0)], ['S', (2, 2)], ['I', (4, 9)], 
               ['O', (1, 1)], ['C', (5, 1)], ['R', (7, 1)], ['R', (9, 3)], 
               ['I', (4, 8)], ['S', (7, 7)], ['C', (8, 4)], ['O', (2, 1)], 
               ['R', (8, 1)], ['R', (8, 2)], ['C', (1, 3)], ['R', (9, 4)]]

dummy_edges = [[17, 10], [16, 10], [19, 11], [7, 12], [1, 12], [5, 9], [5, 3], 
               [14, 18], [15, 8], [17, 5], [19, 14], [7, 0], [5, 15], [14, 17], 
               [15, 17], [2, 6], [2, 17], [4, 13], [4, 7], [6, 15], [6, 5], 
               [13, 14], [18, 6], [4, 6], [2, 13]]

# 변환 실행
converted_nodes, converted_edges = GraphPreprocessing(dummy_nodes, dummy_edges)

# 출력 확인
print("converted_nodes =", converted_nodes)
print("converted_edges =", converted_edges)


converted_nodes = [{'id': 0, 'type': 'H', 'coords': (10, 10)}, {'id': 1, 'type': 'I', 'coords': (5, 8)}, {'id': 2, 'type': 'S', 'coords': (7, 2)}, {'id': 3, 'type': 'C', 'coords': (6, 0)}, {'id': 4, 'type': 'S', 'coords': (2, 7)}, {'id': 5, 'type': 'C', 'coords': (5, 0)}, {'id': 6, 'type': 'S', 'coords': (2, 2)}, {'id': 7, 'type': 'I', 'coords': (4, 9)}, {'id': 8, 'type': 'O', 'coords': (1, 1)}, {'id': 9, 'type': 'C', 'coords': (5, 1)}, {'id': 10, 'type': 'R', 'coords': (7, 1)}, {'id': 11, 'type': 'R', 'coords': (9, 3)}, {'id': 12, 'type': 'I', 'coords': (4, 8)}, {'id': 13, 'type': 'S', 'coords': (7, 7)}, {'id': 14, 'type': 'C', 'coords': (8, 4)}, {'id': 15, 'type': 'O', 'coords': (2, 1)}, {'id': 16, 'type': 'R', 'coords': (8, 1)}, {'id': 17, 'type': 'R', 'coords': (8, 2)}, {'id': 18, 'type': 'C', 'coords': (1, 3)}, {'id': 19, 'type': 'R', 'coords': (9, 4)}]
converted_edges = [{'start': 0, 'end': 7, 'distance': 6.082762530298219, 'road_type': 'urban'}, {'start': 7, 'end': 0, 'distance'

In [17]:
adj = make_adjacency_matrix(dummy_nodes, dummy_edges)
print(f'adj = \n{adj}')

20
adj = 
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0